### ISSUE TITLE
Verify that Autoware Universe can be run with Open AD Kit 1.0

### ISSUE THREAD

**Issue by ghost** [autowarefoundation/AutowareProjects#32] opened 2022-05-12 05:28 UTC
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Verify that Autoware Universe can be run with Open AD Kit 1.0 on the same platforms (ADLINK AVA and Autocore PCU) and with the same CI/CD system. In short, we want to be able to apply the [existing Open AD Kit 1.0 Start Guide](https://gitlab.com/autowarefoundation/autoware_reference_design/-/blob/main/docs/Appendix/Open-AD-Kit-Start-Guide/index.md) to Autoware Universe instead of Autoware.Auto.

### Purpose

As a first step towards the next version of Open AD Kit, we need to confirm that Autoware Universe can be used with the existing Open AD Kit 1.0. In order to do, we need (new) launch files to run Autoware Universe as multiple instances of a single container image, then we need to test the two platforms that were originally supported by Open AD Kit 1.0

### Definition of done

- [x] Provide the commands needed to launch each Autoware Universe stack individually (as per Open AD Kit 1.0) @mitsudome-r 
- [x] Confirm that Autoware Universe can work with TIER IV's CI/CD system @eratostennis 
  - Will be complete after this PR is merged: https://github.com/autowarefoundation/autoware/pull/397 
- [x] Verify that Autoware Universe can be run on the ADLINK AVA platform @ito-san 
- [x] Verify that Autoware Universe can be run on the Autocore PCU platform @Sharrrrk
  - [Test report](https://github.com/autowarefoundation/autoware-projects/files/9247680/Test.report.-.Run.Autoware.universe.on.PCU.pdf)
- [x] Verify that Autoware Universe can be run on a Jetson AGX Orin @Sharrrrk
  - [x] Optional: Verify on a Jetson AGX Xavier @Sharrrrk

**Comment by Sharrrrk** [comment] 2022-05-19 06:32
@LalithVipulananthan I could also verify on Jetson AGX Xavier if required.

**Comment by mitsudome-r** [comment] 2022-06-08 15:56
Here's the list of the launch files that you can use:
https://github.com/autowarefoundation/autoware.universe/tree/main/launch

You can launch them with scenario simulator by following commands:
1. Download map+scenario from this link
2. Modify the path in downloaded scenario.yml to the path of downloaded map
3. Launch each modules:
* Vehicle Module:
```
```
*

**Comment by mitsudome-r** [comment] 2022-06-08 16:03
Here's the list of the launch files that you can use:
https://github.com/autowarefoundation/autoware.universe/tree/main/launch

You can launch them with scenario simulator by following commands:
1. Download map+scenario from [here](https://drive.google.com/file/d/1vWMLbmwJJE5tYO40ypCMxqtmgQPQxhiw/view?usp=sharing)
2. Modify the path in downloaded scenario.yml to the path of downloaded map
3. Launch each modules:
* Vehicle Module:
```
ros2 launch tier4_vehicle_launch vehicle.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit launch_vehicle_interface:=true
```
*  System Module:
```
ros2 launch tier4_system_launch system.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit run_mode:=planning_simulation
```
* API Module:
```
ros2 launch tier4_autoware_api_launch autoware_api.launch.xml init_simulator_pose:=true init_localization_pose:=false
```
* Simulator Module
```
ros2 launch tier4_simulator_launch simulator.launch.xml launch_dummy_perception:=false launch_dummy_vehicle:=false vehicle_info_param_file:=$(ros2 pkg prefix sample_vehicle_description)/share/sample_vehicle_description/config/vehicle_info.param.yaml vehicle_model:=sample_vehicle scenario_simulation:=true
```
* Map Module
```
ros2 launch tier4_map_launch map.launch.py lanelet2_map_path:=$HOME/Downloads/sample_data/map/lanelet2_map.osm pointcloud_map_path:=$HOME//Downloads/sample_data/map/pointcloud_map.pcd
```
* Planning Module
```
ros2 launch tier4_planning_launch planning.launch.xml vehicle_info_param_file:=$(ros2 pkg prefix sample_vehicle_description)/share/sample_vehicle_description/config/vehicle_info.param.yaml
```
* Control Module
```
ros2 launch tier4_control_launch control.launch.py lateral_controller_mode:=mpc_follower vehicle_info_param_file:=$(ros2 pkg prefix sample_vehicle_description)/share/sample_vehicle_description/config/vehicle_info.param.yaml
```
4. Launch Scenario Simulator
```
ros2 launch scenario_test_runner scenario_test_runner.launch.py scenario:=$HOME/Downloads/sample_data/t4v2.yaml architecture_type:=awf/universe launch_rviz:=true launch_autoware:=false record:=false
```

**Comment by ito-san** [comment] 2022-06-14 02:15
@kasperornmeck
The Open AD Kit Start Guide was updated to use meta-adlink-ampere v1.4 (on 17 Jan) and meta-ewaol v0.2.4 (on 22 Mar) by this MR(
https://gitlab.com/autowarefoundation/autoware_reference_design/-/merge_requests/11).
Looks like an old version, can I use a master branch? or latest tag?(meta-adlink-ampere v2.1 (on 27 Jan) and meta-ewaol v1.0 (on 25 May)).

**Comment by ito-san** [comment] 2022-06-16 02:12
Successfully built with the latest master of meta-adlink-ampere and meta-ewaol.
  meta-adlink-ampere: commit hash=2c350d2453d1931a68177a9f8e9d6c44fd1410b9
  meta-ewaol: commit hash=26b2d08f70dcc0e046da8544c968064773c7cc45

And Successfully booted with Xen hypervisor.
```console
root@ava:~# uname -a
Linux ava 5.15.23-ampere-lts-standard #1 SMP PREEMPT Mon Apr 25 12:10:09 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
root@ava:~# xl list
Name                                        ID   Mem VCPUs	State	Time(s)
Domain-0                                     0  4096    32     r-----     639.6
ewaol-guest-vm1                              1  6143     4     -b----     102.3
```

**Comment by ito-san** [comment] 2022-06-22 08:42
Wating docker images for arm64 and scenario simulator from CI/CD team.

**Comment by ito-san** [comment] 2022-06-29 12:30
Still waiting for docker images, requesting 2 images. One is arm64 based image for Autoware and another is x86/64 image for the scenario simulator.

**Comment by xmfcx** [comment] 2022-06-29 15:34
@ito-san wrote:
> One is arm64 based image for Autoware

Autoware images are located here: https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe

Latest autoware arm build is in here: https://github.com/orgs/autowarefoundation/packages/container/autoware-universe/26844652?tag=galactic-latest-prebuilt-cuda-arm64

**Comment by ghost** [comment] 2022-06-30 06:59
Hi @Sharrrrk ! Have you been able to make any progress with your task of testing Autoware Universe with the Autocore PCU? Also, could you give me an idea when you will be able to test the Jetson AGX Xavier as well?

**Comment by ito-san** [comment] 2022-07-02 08:02
Now I'm getting an error regarding lanelet2. Investigating.
![Image](https://user-images.githubusercontent.com/57388357/176992207-ece0522b-1cae-4c2c-bba6-bd3c62bccbf5.png)
![Image](https://user-images.githubusercontent.com/57388357/176992460-aa75fc17-30e0-493a-a7b9-7c78e84b5054.png)

Left: AVA platform, Right: My laptop (verified map files are correct using planning simulator on my laptop)
Seems to be the same. Curious.
![Image](https://user-images.githubusercontent.com/57388357/176992592-a9b055c6-66f5-4361-80a7-0664052f1c66.png)

**Comment by ito-san** [comment] 2022-07-02 08:23
On my laptop. Having the same error but correctly shown. Seems to be another cause.
![Image](https://user-images.githubusercontent.com/57388357/176992846-64d4593f-a8bc-4322-ab94-0c9c2eb66eb4.png)
![Image](https://user-images.githubusercontent.com/57388357/176992860-3c5d9331-9d9a-4a3b-a1f5-15a6e3479c54.png)

**Comment by ghost** [comment] 2022-07-05 04:44
@ito-san Thank you for your updates!

1. Were you able to get an x86/64 image for the Scenario Simulator?
2. If you load that lanelet2 map into Vector Map Builder, does VMB report the same errors/warnings about linestrings needing more than 3 different points?

**Comment by ito-san** [comment] 2022-07-06 09:30
@LalithVipulananthan 
> 1. Were you able to get an x86/64 image for the Scenario Simulator?

I intend to build from source.
[Installation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/scenario-simulation/planning-simulation/installation/)
And run.
[Scenario test simulation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/scenario-simulation/planning-simulation/scenario-test-simulation/)

> 2.  If you load that lanelet2 map into Vector Map Builder, does VMB report the same errors/warnings about linestrings needing more than 3 different points?

Looks like no problem in Vector Map Builder.
![image](https://user-images.githubusercontent.com/57388357/177517539-9a2c8d57-083d-4adc-ac4f-b1184a4a3145.png)

Next step, I will try to run Autoware with native environment, Ubuntu 20.04 on arm.

**Comment by Sharrrrk** [comment] 2022-07-06 09:37
> Hi @Sharrrrk ! Have you been able to make any progress with your task of testing Autoware Universe with the Autocore PCU? Also, could you give me an idea when you will be able to test the Jetson AGX Xavier as well?

@LalithVipulananthan I have just tested to launch all the modules on Autocore PCU and AGX Xavier, looks good so far. Next I will try to run all the modules with scenario simulator together.

**Comment by ito-san** [comment] 2022-07-12 10:10
Successfully run with planning_simulator on single container using old version of yocto packages
|package|used|latest|
|---|---|---|
|meta-adlink-ampere|v1.4|v2.1|
|meta-ewaol|v0.2.4|v1.0|

Here is what I've done.
On the AVA
```console
docker run --rm -it --net host -v /home/root/map:/map -v /home/root/cyclonedds:/etc/cyclonedds cbb36312a783 /bin/bash -c "export CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml; export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp; source install/setup.bash; ros2 launch autoware_launch planning_simulator.launch.xml map_path:=/map/sample-map-planning vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit launch_rviz:=false"
```
On the host
```console
rviz2 -d src/launcher/autoware_launch/autoware_launch/rviz/autoware.rviz
```

https://user-images.githubusercontent.com/57388357/178464934-7853cdee-b404-4f33-a1bd-d387d23f4232.mp4

**Comment by ghost** [comment] 2022-07-19 13:33
@kasperornmeck Would you be able to investigate why the Lanelet2 map did not display on AVA using the latest yocto builds, but did work with a previous version? If @ito-san can provide details of his testing and log files, that would be a good starting point, but failing that, do you have time to follow the same steps to see if you can repro the problem or not?

**Comment by kaspermeck-arm** [comment] 2022-07-19 14:43
@LalithVipulananthan 
Yes, looking through the documentation in this thread, I'd say it's sufficient for me to replicate. I would need is access to the container images (on AVA and on the host) and any data files.

**Comment by ito-san** [comment] 2022-07-27 07:07
@kasperornmeck I'm attaching console outputs of the old and new version of yocto packages. The outputs are when I simply launched autoware.

[ok_in_old_version.log](https://github.com/autowarefoundation/autoware-projects/files/9195901/ok_in_old_version.log)
[ng_in_new_version.log](https://github.com/autowarefoundation/autoware-projects/files/9195905/ng_in_new_version.log)

**Comment by kaspermeck-arm** [comment] 2022-07-27 19:07
@ito-san, I'm having issues accessing these files, could you send them to my email address instead? kasper.ornsteinmecklenburg[at]arm.com
Thanks!

**Comment by mitsudome-r** [comment] 2022-07-28 07:14
FYI, it seems like there was issues with Control module which caused autoware_state to never transition from Planning -> WaitForEngage for past few days. It should be fixed now with https://github.com/autowarefoundation/autoware.universe/pull/1450

**Comment by kaspermeck-arm** [comment] 2022-07-28 13:45
@mitsudome-r @ito-san 
Does that mean that we can rule out that the change in behavior wasn't due to the EWAOL version?

**Comment by mitsudome-r** [comment] 2022-07-28 23:31
@kasperornmeck I'm not sure what's the current failure in EWAOL, but if you are talking about [Lalith's comment](https://github.com/autowarefoundation/autoware-projects/issues/32#issuecomment-1189061103), at least the fix that I mentioned has nothing to do with lanelet2 map.

**Comment by mitsudome-r** [comment] 2022-07-28 23:33
@ito-san FYI, the newest docker image is pushed yesterday if you would like to try out the newest version of Autoware. https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe/30491081?tag=galactic-20220728-prebuilt-cuda-arm64

**Comment by ito-san** [comment] 2022-08-02 02:29
@mitsudome-r @LalithVipulananthan 
Thank you for your kind support.
Made a little bit changes from OpenADKit 1.0. Confirmed that Autoware.universe runs as multiple k3 clusters and scenario_simulator_v2 works.
![Image](https://user-images.githubusercontent.com/57388357/182278579-c00c8f43-6f19-41fa-a164-667b1f7a600b.png)


https://user-images.githubusercontent.com/57388357/182279632-dbd0b2de-0792-4139-9469-4af99be2ddfe.mp4

**Comment by kaspermeck-arm** [comment] 2022-08-02 20:51
@ito-san 
This is really neat, well done! :)
Is there documentation for me to replicate this? I can do the OoB testing and give feedback on the documentation.

**Comment by Sharrrrk** [comment] 2022-08-03 03:17
My test report on PCU is here:
[Test report - Run Autoware.universe on PCU.pdf](https://github.com/autowarefoundation/autoware-projects/files/9247680/Test.report.-.Run.Autoware.universe.on.PCU.pdf)

Test based on latest docker images:
- autoware-universe:galactic-latest-prebuilt-arm64
- scenario_simulator_v2:galactic

**Comment by Sharrrrk** [comment] 2022-08-03 03:19
@LalithVipulananthan I've got a Jetson AGX Orin lately, I could do the test on it if requried.

**Comment by ghost** [comment] 2022-08-03 13:29
@Sharrrrk Hi Shark, if you can spare the time to test on the AGX Orin as well then that would be very much appreciated! If you can also test on an AGX Xavier afterwards, then that would be awesome.

**Comment by Sharrrrk** [comment] 2022-08-12 10:23
Test report on Orin:
[Test report - Run AW.universe with OpenADKit v1.0 on Orin.pdf](https://github.com/autowarefoundation/autoware-projects/files/9420690/Test.report.-.Run.AW.universe.with.OpenADKit.v1.0.on.Orin.pdf)

Test report on Xavier:
[Test report - Run AW.universe with OpenADKit v1.0 on Xavier .pdf](https://github.com/autowarefoundation/autoware-projects/files/9420693/Test.report.-.Run.AW.universe.with.OpenADKit.v1.0.on.Xavier.pdf)

**Comment by Sharrrrk** [comment] 2022-08-12 10:24
@LalithVipulananthan  All the tests assigned to me are finised.

**Comment by ito-san** [comment] 2022-08-14 13:18
@LalithVipulananthan @kasperornmeck 
The pdf version of eSync OTA Update is available now.
[eSync OTA Update.pdf](https://drive.google.com/file/d/1hOvJChQthK3h-FWhEACmKdxoFV8dcD36/view?usp=sharing) (accessible only to the members who can access `AWF - Open AD Kit` Google Drive)

**Comment by ito-san** [comment] 2022-08-17 09:21
@kasperornmeck Confirmed that Autoware.universe runs on EWAOL 1.0 baremetal image.

https://user-images.githubusercontent.com/57388357/185083253-27234791-6f5e-47ce-baf8-454e0ca10140.mp4

**Comment by ito-san** [comment] 2022-08-17 09:47
@kasperornmeck Also confirmed arm64 version of `scenario_simulator_v2` works on AVA platform.

https://user-images.githubusercontent.com/57388357/185088263-c9dddcf6-b82d-45c6-ac6b-9437f50b7c72.mp4

**Comment by kaspermeck-arm** [comment] 2022-08-17 15:16
@ito-san very nice! :)

Does that mean that we can conclude that it is Xen (virtualization) which prevented Autoware.Universe from working properly on EWAOL v1.0?

**Comment by ito-san** [comment] 2022-08-18 00:05
@kasperornmeck Yes, maybe.

**Comment by NilaySener** [comment] 2022-08-18 10:54
@Sharrrrk Hi,  I was trying to run autoware modules with OpenAD kit, referring to the Orin test report you shared.The .pdf file you provided has incomplete commands due to the format of the file. 

e.g
![unknown](https://user-images.githubusercontent.com/106528015/185378310-6748fc51-f24e-4f4a-af22-951b776f8954.png)


 Can you share Orin's test report in a file format where I can access all the commands?

**Comment by Sharrrrk** [comment] 2022-08-25 01:49
@NilaySener you are right, I updated the report here:
[Test report - Run AW.universe with OpenADKit v1.0 on Orin.pdf](https://github.com/autowarefoundation/autoware-projects/files/9420690/Test.report.-.Run.AW.universe.with.OpenADKit.v1.0.on.Orin.pdf)
Please feel free to ask if you have any other concerns.

**Comment by NilaySener** [comment] 2022-08-26 15:33
@Sharrrrk Thank you for the report you shared. I followed the steps on Orin and got the same results.

**Comment by Sharrrrk** [comment] 2022-09-06 08:47
All tasks finished.

**Closed as completed by Sharrrrk** 2022-09-06 08:47 UTC
